#---
#experiment:
#  name: tiger_detector_exp1
#  folder: /home/cortwave/projects/tigerc/tiger_detection/detection_exp
#phase: test
#save_folder: eval
#
#data:
#    - name: tigerss
#      ann_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/val.json
#      img_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/detection_img/trainval
#
#model:
#    load_weights: False
#    weights_path: /home/cortwave/projects/tigerc/tiger_detection/detection_exp/tiger_detector_exp1/best.h5
#    pretrain_weights:  /home/cortwave/projects/tigerc/tiger_detection/tigers_code/mobilenet_v2.pth.tar
#    num_classes: 2
#    img_size: 512
#    feature_maps: 6
#    name: retina_net
#    backbone: mobilenet
#    encoder_depth: 50
#    pretrained: True
#    visual_thr: 0.05
#    filter_thr: 0.01
#    filepath: /home/cortwave/projects/tigerc/tiger_detection/detection_exp/tiger_detector_exp1/best.h5
---
experiment:
  name: tiger_detector_exp1
  folder: /home/cortwave/projects/tigerc/tiger_detection/detection_exp
phase: test
save_folder: eval

data:
    - name: tigerss
      ann_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/test_set.json
      img_path: /home/cortwave/projects/tigerc/tiger_detection/tigers_data/test

model:
    load_weights: False
    weights_path: /home/cortwave/projects/tigerc/tiger_detection/detection_exp/tiger_detector_exp1/best.h5
    pretrain_weights:  /home/cortwave/projects/tigerc/tiger_detection/tigers_code/mobilenet_v2.pth.tar
    num_classes: 2
    img_size: 512
    feature_maps: 6
    name: retina_net
    backbone: mobilenet
    encoder_depth: 50
    pretrained: True
    visual_thr: 0.05
    filter_thr: 0.01
    filepath: /home/cortwave/projects/tigerc/tiger_detection/detection_exp/tiger_detector_exp1/best.h5
